# Rspamd milter headers
# Remove headers that could leak information

extended_spam_headers = false;

remove_headers {
    "X-Rspamd-Pre-Result" = 0;
    "X-Rspamd-Server" = 0;
    "X-Rspamd-Queue-Id" = 0;
    "X-Spam-Status" = 0;
    "X-Spam-Score" = 0;
    "X-Spam-Flag" = 0;
}
