# Dovecot LDA (Local Delivery Agent) configuration

protocol lda {
    mail_plugins = $mail_plugins sieve quota
    
    # No logging
    log_path = /dev/null
    info_log_path = /dev/null
}

# Sieve plugin
plugin {
    sieve = file:~/sieve;active=~/.dovecot.sieve
    sieve_default = /etc/dovecot/sieve/default.sieve
    sieve_global_dir = /etc/dovecot/sieve/global/
}
