# Dovecot IMAP configuration

protocol imap {
    mail_plugins = $mail_plugins quota imap_quota
    
    # Max connections per IP (high for webmail)
    mail_max_userip_connections = 20
}

service imap-login {
    inet_listener imap {
        # Disable plain IMAP (only IMAPS)
        port = 0
    }
    
    inet_listener imaps {
        port = 993
        ssl = yes
    }
    
    # Performance
    service_count = 1
    process_min_avail = 2
}

service imap {
    # vsz_limit = 512M
}
