# Dovecot LMTP configuration

protocol lmtp {
    mail_plugins = $mail_plugins sieve quota
    
    # No logging
    log_path = /dev/null
    info_log_path = /dev/null
}

service lmtp {
    # Listen on all interfaces for Docker networking
    inet_listener lmtp {
        address = *
        port = 24
    }
    
    user = vmail
}
