# Dovecot POP3 configuration

protocol pop3 {
    mail_plugins = $mail_plugins quota
    
    # POP3 UIDL format
    pop3_uidl_format = %08Xu%08Xv
}

service pop3-login {
    inet_listener pop3 {
        # Disable plain POP3 (only POP3S)
        port = 0
    }
    
    inet_listener pop3s {
        port = 995
        ssl = yes
    }
}
